version: '3.8'

services:
  backend:
    build:
      context: ./backend-dev
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=localhost
      - DATABASE_PORT=5434
      - DATABASE_USER=luka
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=db2
    depends_on:
      - db
    volumes:
      - ./backend-dev:/usr/src/app
      - /usr/src/app/node_modules


  db:
    image: postgres:13
    environment:
      POSTGRES_DB: db2
      POSTGRES_USER: luka
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5434"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
